{
	"version": 1601847406,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/nave-sheet0.png",
		"images/inimigo-sheet0.png",
		"images/inimigo-sheet1.png",
		"images/bala-sheet0.png",
		"images/balainim-sheet0.png",
		"images/estrela-sheet0.png",
		"images/nomegame-sheet0.png",
		"images/sp_jogar-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/ponto_sp-sheet0.png",
		"images/font_1.png",
		"images/sp_reiniciar-sheet0.png",
		"images/sp_register_-sheet0.png",
		"images/ranking-sheet0.png",
		"images/rk-sheet0.png",
		"images/jogar_n-sheet0.png",
		"media/abandoned hopes.ogg",
		"media/hit damage 1.ogg",
		"media/text 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"made tommy black outline_personal use.otf",
		"made tommy black_personal use.otf",
		"made tommy bold outline_personal use.otf",
		"made tommy bold_personal use.otf",
		"made tommy extrabold outline_personal use.otf",
		"made tommy extrabold_personal use.otf",
		"made tommy light outline_personal use.otf",
		"made tommy light_personal use.otf",
		"made tommy medium outline_personal use.otf",
		"made tommy medium_personal use.otf",
		"made tommy regular outline_personal use.otf",
		"made tommy regular_personal use.otf",
		"made tommy thin outline_personal use.otf",
		"made tommy thin_personal use.otf"
	]
}